"""Ajout du champ verification_sent_at

Revision ID: 9461f6e4e85b
Revises: 4387f542407d
Create Date: 2025-10-18 21:40:57.556824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9461f6e4e85b'
down_revision: Union[str, Sequence[str], None] = '4387f542407d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_sent_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_sent_at')
    # ### end Alembic commands ###
